receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  debug:
    verbosity: detailed  # Optional: use 'normal', 'detailed', or 'basic'

  otlphttp:
    endpoint: "http://tempo:4318" # Tempo for tracing

  prometheus:
    endpoint: "0.0.0.0:9464" # Prometheus for metrics

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
