server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces

compactor:
  compaction:
    block_retention: 48h  # Retain traces for 48 hours

ingester:
  trace_idle_period: 30s
  max_block_bytes: 1_000_000
  max_block_duration: 5m

overrides:
  max_traces_per_user: 100000
