name: Build and Test .NET Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies Catalog
      run: dotnet restore Catalog/Presentation/Catalog.Api/Catalog.Api.csproj
      
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies Catalog
        run: dotnet restore
      - name: Build
        run: dotnet build Catalog/Presentation/Catalog.Api/Catalog.Api.csproj --no-restore
      - name: Test
        run: dotnet test Catalog/Presentation/Catalog.Api/Catalog.Api.csproj --no-restore --verbosity normal